---
# logging settings
log:
  filename: /Users/sw/go/log/kd-microservice.log.log
  level: DEBUG

# database settings
database:
  driver: ${DB_DRIVER}
  host: ${DB_HOST}
  port: ${DB_PORT}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  dbname: ${DB_NAME}

# server settings
server:
  port: 5600
  env: prd
  log-output: console
  output-file-path: ./kd-microservice.log
  config-path: .
  service-name: kd-microservice

# Access Control SETTING
access-control:
  allow-origin: "*"
  allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
  allow-credentials: "true"
  allow-headers: "Origin, Content-Type, Authorization"
  request-headers: "Origin, Content-Type, Authorization"

route:
  site: "/shipment-svc/api/v1"

cache:
  redis:
    host: ${REDIS_HOST}
    user: 
    password: ${REDIS_PASSWORD}
    port: 6379
    index:
      primary: 0
    is-active : true
    expired-in-minute: 
      default : 1440
      shipping-rate : 1440
    base-key: shipping-svc

shipper:
  auth:
    key: X-API-Key
    value: ${SHIPPER_AUTH_VALUE}
  base: ${SHIPPER_BASE}
  path:
    get-pricing-domestic: /v3/pricing/domestic
    order: /v3/order
    order-detail: /v3/order/{orderID}
    pick-up-timeslot: /v3/pickup/timeslot
    cancel-pickup: /v3/pickup/cancel
  setting:
    package-type: 3
  webhook:
    update-status-endpoint: https://shipping-api.medkomtek-stg.com/shipment-svc/api/v1/public/webhook/shipper

grab:
  auth:
    client-id: ${GRAB_CLIENT_ID}
    client-secret: ${GRAB_CLIENT_SECRET}
    grant-type: client_credentials
    scope: grab_express.partner_deliveries
    webhook-client-id: ${GRAB_WEBHOOK_CLIENT_ID}
    webhook-client-secret: ${GRAB_WEBHOOK_CLIENT_SECRET}
  base: https://partner-api.stg-myteksi.com
  path:
    auth: /grabid/v1/oauth2/token
    get-delivery-quote: /grab-express-sandbox/v1/deliveries/quotes
    create-delivery: /grab-express-sandbox/v1/deliveries
    delivery-detail: /grab-express-sandbox/v1/deliveries/{deliveryID}

dapr:
  endpoint:
    publish-kafka: http://localhost:3500/v1.0/publish/kafka-pubsub/{topic-name}?metadata.rawPayload=true
  topic :
    update-order-shipping: queueing.shipment.order-shipping-update.{channel-code}

setting:
  shipping-type: 
  - instant
  - same_day
  - next_day
  - regular
  - economy
  - cargo
