#logging settings
log:
  filename: /Users/sw/go/log/kd-microservice.log.log
  level: DEBUG

#database settings
database:
  driver: ${DB_DRIVER}
  host: ${DB_HOST}
  port: ${DB_PORT}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  dbname: ${DB_NAME}

#server settings
server:
  port: 5600
  env: prd
  log-output: console
  output-file-path: ./kd-microservice.log
  config-path: .
  service-name: kd-microservice

#Access Control SETTING
access-control:
  allow-origin: "*"
  allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
  allow-credentials: "true"
  allow-headers: "Origin, Content-Type, Authorization"
  request-headers: "Origin, Content-Type, Authorization"
