basePath: /
definitions:
  SaveCourierCoverageCodeRequest:
    properties:
      code1:
        description: |-
          Code 1 of the Courier Coverage Code
          in: string
        type: string
        x-go-name: Code1
      code2:
        description: |-
          Code 2 of the Courier Coverage Code
          in: string
        type: string
        x-go-name: Code2
      code3:
        description: |-
          Code 3 of the Courier Coverage Code
          in: string
        type: string
        x-go-name: Code3
      code4:
        description: |-
          Code 4 of the Courier Coverage Code
          in: string
        type: string
        x-go-name: Code4
      code5:
        description: |-
          Code 5 of the Courier Coverage Code
          in: string
        type: string
        x-go-name: Code5
      code6:
        description: |-
          Code 6 of the Courier Coverage Code
          in: string
        type: string
        x-go-name: Code6
      country_code:
        description: |-
          Country code of the Courier Coverage Code
          required: True
          in: string
        type: string
        x-go-name: CountryCode
      courier_uid:
        description: |-
          Courier UID of the Courier
          required: True
          in: string
        type: string
        x-go-name: CourierUID
      description:
        description: |-
          Description of the Courier Coverage Code
          in: string
        type: string
        x-go-name: Description
      postal_code:
        description: |-
          Postal code of the Courier Coverage Code
          required: True
          in: string
        type: string
        x-go-name: PostalCode
    type: object
    x-go-package: go-klikdokter/app/model/request
  SaveCourierRequest:
    properties:
      code:
        description: |-
          Code of the courier
          in: string
        type: string
        x-go-name: Code
      courier_api_intergration:
        description: |-
          Courier Api Integration of the Courier
          in: integer
        format: int64
        type: integer
        x-go-name: CourierApiIntegration
      courier_name:
        description: |-
          Name of the courier
          in: string
        type: string
        x-go-name: CourierName
      courier_type:
        description: |-
          type of courier
          in: string
        type: string
        x-go-name: CourierType
      hide_purpose:
        description: |-
          Hide purpose of the Courier
          in: integer
        format: int64
        type: integer
        x-go-name: HidePurpose
      logo:
        description: |-
          Logo of courier
          in: string
        type: string
        x-go-name: Logo
      provide_airwaybill:
        description: |-
          Provide Airwaybill of the Courier
          in: integer
        format: int64
        type: integer
        x-go-name: ProvideAirwaybill
      status:
        description: |-
          Courier status
          in: int
        format: int64
        type: integer
        x-go-name: Status
      uid:
        description: |-
          Uid of the courỉe, use this on UPDATE function
          in: int32
        type: string
        x-go-name: Uid
      use_geocoodinate:
        description: |-
          Geo Coodinate of the Courier
          in: string
        format: int64
        type: integer
        x-go-name: UseGeocoodinate
    type: object
    x-go-package: go-klikdokter/app/model/request
  SaveDoctorRequest:
    properties:
      gender:
        description: |-
          Gender of the doctor
          in: string
        type: string
        x-go-name: Gender
      name:
        description: |-
          Name of the doctor
          in: string
        type: string
        x-go-name: Name
      uid:
        description: |-
          Uid of the product, use this on UPDATE function
          in: int32
        type: string
        x-go-name: Uid
    type: object
    x-go-package: go-klikdokter/app/model/request
  SaveProductRequest:
    properties:
      name:
        description: |-
          Name of the product
          in: string
        type: string
        x-go-name: Name
      sku:
        description: |-
          Sku of the product
          in: string
        type: string
        x-go-name: Sku
      uid:
        description: |-
          Uid of the product, use this on UPDATE function
          in: int32
        type: string
        x-go-name: Uid
      uom:
        description: |-
          Uom of the product
          in: string
        type: string
        x-go-name: Uom
      weight:
        description: |-
          Weight of the product
          in: int32
        format: int32
        type: integer
        x-go-name: Weight
    type: object
    x-go-package: go-klikdokter/app/model/request
host: localhost:5600
info:
  title: 'KD Boilerplate Go kit:'
  version: "1.0"
paths:
  /courier/{id}:
    put:
      description: Update courier
      operationId: UpdateCourierRequest
      responses:
        "200":
          $ref: '#/responses/SuccessResponse'
        "401":
          $ref: '#/responses/SuccessResponse'
      tags:
      - courier-update
  /courier/courier:
    post:
      description: Manage Courier
      operationId: ManagedCourierRequest
      responses:
        "201":
          $ref: '#/responses/SuccessResponse'
        "401":
          $ref: '#/responses/SuccessResponse'
      tags:
      - Courier
  /courier/courier-coverage-code/:
    get:
      description: List products
      operationId: CourierCoverageCodeListRequest
      parameters:
      - description: Maximun records per page
        format: int64
        in: path
        name: Limit
        required: true
        type: integer
      - description: Page No
        format: int64
        in: path
        name: Page
        required: true
        type: integer
      - example: name asc, uom desc
        in: path
        name: Sort
        required: true
        type: string
      responses:
        "200":
          $ref: '#/responses/PaginationResponse'
        "401":
          $ref: '#/responses/SuccessResponse'
      tags:
      - Courier-Coverage-Code
    post:
      description: Update courier coverage by uid
      operationId: SaveCourierCoverageCodeRequest
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/SaveCourierCoverageCodeRequest'
        x-go-name: Body
      responses:
        "200":
          $ref: '#/responses/SuccessResponse'
        "401":
          $ref: '#/responses/SuccessResponse'
      tags:
      - Courier-Coverage-Code
  /courier/courier-coverage-code/{uid}:
    get:
      description: Get Courier Coverage Code by uid
      operationId: CourierCoverageCodeByIDParam
      parameters:
      - description: 'name: id'
        in: path
        name: uid
        required: true
        type: string
        x-go-name: UId
      responses:
        "200":
          $ref: '#/responses/CourierCoverageCode'
        "401":
          $ref: '#/responses/SuccessResponse'
      tags:
      - Courier-Coverage-Code
    put:
      description: Update courier coverage by uid
      operationId: SaveCourierCoverageCodeRequest
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/SaveCourierCoverageCodeRequest'
        x-go-name: Body
      responses:
        "200":
          $ref: '#/responses/SuccessResponse'
        "401":
          $ref: '#/responses/SuccessResponse'
      tags:
      - Courier-Coverage-Code
  /courier/courier/{id}:
    delete:
      description: Delete product
      operationId: byParamDelete
      parameters:
      - description: 'name: id'
        in: path
        name: id
        required: true
        type: string
        x-go-name: Id
      responses:
        "200":
          $ref: '#/responses/SuccessResponse'
        "401":
          $ref: '#/responses/SuccessResponse'
      tags:
      - product-delete
    get:
      description: Get Courier
      operationId: Courier
      responses:
        "201":
          $ref: '#/responses/SuccessResponse'
        "401":
          $ref: '#/responses/SuccessResponse'
      tags:
      - Get-Courier
  /doctors/:
    post:
      description: Create Doctor
      operationId: SaveDoctorRequest
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/SaveDoctorRequest'
        x-go-name: Body
      responses:
        "201":
          $ref: '#/responses/SuccessResponse'
        "401":
          $ref: '#/responses/SuccessResponse'
      tags:
      - Doctor
  /doctors/{id}:
    get:
      description: Get Doctor
      operationId: doctor
      parameters:
      - description: 'name: id'
        in: path
        name: id
        required: true
        type: string
        x-go-name: Id
      responses:
        "201":
          $ref: '#/responses/SuccessResponse'
        "401":
          $ref: '#/responses/SuccessResponse'
      tags:
      - Get-Doctor
  /products/:
    post:
      description: Create product
      operationId: SaveProductRequest
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/SaveProductRequest'
        x-go-name: Body
      responses:
        "201":
          $ref: '#/responses/SuccessResponse'
        "401":
          $ref: '#/responses/SuccessResponse'
      tags:
      - product
  /products/{id}:
    delete:
      description: Delete product
      operationId: byParamDelete
      parameters:
      - description: 'name: id'
        in: path
        name: id
        required: true
        type: string
        x-go-name: Id
      responses:
        "200":
          $ref: '#/responses/SuccessResponse'
        "401":
          $ref: '#/responses/SuccessResponse'
      tags:
      - product-delete
    get:
      description: Get product
      operationId: byParamGet
      parameters:
      - description: 'name: id'
        in: path
        name: id
        required: true
        type: string
        x-go-name: Id
      responses:
        "200":
          $ref: '#/responses/SuccessResponse'
        "401":
          $ref: '#/responses/SuccessResponse'
      tags:
      - get-product
      - product
    put:
      description: Update product
      operationId: UpdateProductRequest
      parameters:
      - description: 'name: id'
        in: path
        name: id
        required: true
        type: string
        x-go-name: Id
      - in: body
        name: body
        schema:
          $ref: '#/definitions/SaveProductRequest'
        x-go-name: Body
      responses:
        "200":
          $ref: '#/responses/SuccessResponse'
        "401":
          $ref: '#/responses/SuccessResponse'
      tags:
      - product-update
  /products/list:
    get:
      description: List products
      operationId: productList
      responses:
        "200":
          $ref: '#/responses/SuccessResponse'
        "401":
          $ref: '#/responses/SuccessResponse'
      tags:
      - product
produces:
- application/json
schemes:
- http
swagger: "2.0"
