definitions:
  entity.CourierService:
    properties:
      ETD_Max:
        description: |-
          ETD Max of the Courier Service
          in: float64
        type: number
      ETD_Min:
        description: |-
          ETD Min of the Courier Service
          in: float64
        type: number
      cancelable:
        description: |-
          Cancelable of the Courier Service
          in: integer
        type: integer
      cod_available:
        description: |-
          Cod Available of the Courier Service
          in: integer
        type: integer
      courier_id:
        description: |-
          Courier Id of the Courier Service
          in: int
        type: integer
      courier_name:
        description: |-
          Courier Name of the Courier Service
          in: string
        type: string
      end_time:
        description: |-
          End Time of the Courier Service
          in: time
        type: string
      insurance:
        description: |-
          Insurance of the Courier Service
          in: integer
        type: integer
      insurance_fee:
        description: |-
          Insurance Fee of the Courier Service
          in: float64
        type: number
      insurance_fee_type:
        description: |-
          Insurance Fee Type of the Courier Service
          in: string
        type: string
      insurance_min:
        description: |-
          Insurance Min of the Courier Service
          in: float64
        type: number
      is_deleted:
        type: boolean
      logo:
        description: |-
          Logo of the Courier Service
          in: string
        type: string
      max_distance:
        description: |-
          Max Distance of the Courier Service
          in: float64
        type: number
      max_purchase:
        description: |-
          Max Purchase of the Courier Service
          in: float64
        type: number
      max_volume:
        description: |-
          Max Volume of the Courier Service
          in: float64
        type: number
      max_weight:
        description: |-
          Max Weight of the Courier Service
          in: float64
        type: number
      min_purchase:
        description: |-
          Min Purchase of the Courier Service
          in: float64
        type: number
      prescription_allowed:
        description: |-
          Prescription Allowed of the Courier Service
          in: integer
        type: integer
      repickup:
        description: |-
          Repickup Fee of the Courier Service
          in: float64
        type: number
      shipping_code:
        description: |-
          Shipping Code of the Courier Service
          in: string
        type: string
      shipping_description:
        description: |-
          Shipping Description of the Courier Service
          in: string
        type: string
      shipping_name:
        description: |-
          Shipping Name of the Courier Service
          in: string
        type: string
      shipping_type:
        description: |-
          Shipping Type of the Courier Service
          in: string
        type: string
      start_time:
        description: |-
          Start Time of the Courier Service
          in: time
        type: string
      status:
        description: |-
          Status of the Courier Service
          in: integer
        type: integer
      tracking_available:
        description: |-
          Tracking Available of the Courier Service
          in: integer
        type: integer
      uid:
        description: |-
          UID of the product
          in: int64
        type: string
    type: object
  message.Message:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  request.CourierServiceListRequest:
    properties:
      limit:
        description: |-
          Maximun records per page
          in: int32
        maximum: 100
        minimum: 1
        type: integer
      page:
        description: |-
          Page No
          in: int32
        minimum: 1
        type: integer
      shippingType:
        description: |-
          Shipping type
          in: string
        type: string
      sort:
        description: |-
          Sort fields, example: name asc, uom desc
          in: string
        type: string
      status:
        description: |-
          Courier status
          in: int
        type: integer
    type: object
  request.GetCourierServiceRequest:
    properties:
      id:
        description: |-
          name: id
          in: path
          required: true
        type: string
    type: object
  request.SaveCourierServiceRequest:
    properties:
      ETD_Max:
        description: |-
          ETD Max of the Courier Service
          in: float64
        type: number
      ETD_Min:
        description: |-
          ETD Min of the Courier Service
          in: float64
        type: number
      cancelable:
        description: |-
          Cancelable of the Courier Service
          in: integer
        type: integer
      cod_available:
        description: |-
          Cod Available of the Courier Service
          in: integer
        type: integer
      courier_id:
        description: |-
          Courier Id of the Courier Service
          in: int
        type: integer
      courier_name:
        description: |-
          Courier Name of the Courier Service
          in: string
        type: string
      created_at:
        description: |-
          Created At of the Courier Service
          in: time
        type: string
      created_by:
        description: |-
          Created By Type of the Courier Service
          in: string
        type: string
      end_time:
        description: |-
          End Time of the Courier Service
          in: time
        type: string
      insurance:
        description: |-
          Insurance of the Courier Service
          in: integer
        type: integer
      insurance_fee:
        description: |-
          Insurance Fee of the Courier Service
          in: float64
        type: number
      insurance_fee_type:
        description: |-
          Insurance Fee Type of the Courier Service
          in: string
        type: string
      insurance_min:
        description: |-
          Insurance Min of the Courier Service
          in: float64
        type: number
      logo:
        description: |-
          Logo of the Courier Service
          in: string
        type: string
      max_distance:
        description: |-
          Max Distance of the Courier Service
          in: float64
        type: number
      max_purchase:
        description: |-
          Max Purchase of the Courier Service
          in: integer
        type: number
      max_volume:
        description: |-
          Max Volume of the Courier Service
          in: float64
        type: number
      max_weight:
        description: |-
          Max Weight of the Courier Service
          in: float64
        type: number
      min_purchase:
        description: |-
          Min Purchase of the Courier Service
          in: integer
        type: number
      prescription_allowed:
        description: |-
          Prescription Allowed of the Courier Service
          in: integer
        type: integer
      repickup:
        description: |-
          Repickup Fee of the Courier Service
          in: float64
        type: number
      shipping_code:
        description: |-
          Shipping Code of the Courier Service
          in: string
        type: string
      shipping_description:
        description: |-
          Shipping Description of the Courier Service
          in: string
        type: string
      shipping_name:
        description: |-
          Shipping Name of the Courier Service
          in: string
        type: string
      shipping_type:
        description: |-
          Shipping Type of the Courier Service
          in: string
        type: string
      start_time:
        description: |-
          Start Time of the Courier Service
          in: time
        type: string
      status:
        description: |-
          Status of the Courier Service
          in: integer
        type: integer
      tracking_available:
        description: |-
          Tracking Available of the Courier Service
          in: integer
        type: integer
      uid:
        description: |-
          Uid of the Courier Service, use this on UPDATE function
          in: int32
        type: string
      updated_at:
        description: |-
          Updated At of the Courier Service
          in: time
        type: string
      updated_by:
        description: |-
          Updated By Type of the Courier Service
          in: string
        type: string
    type: object
  request.UpdateCourierServiceRequest:
    properties:
      ETD_Max:
        description: |-
          ETD Max of the Courier Service
          in: float64
        type: number
      ETD_Min:
        description: |-
          ETD Min of the Courier Service
          in: float64
        type: number
      cancelable:
        description: |-
          Cancelable of the Courier Service
          in: integer
        type: integer
      cod_available:
        description: |-
          Cod Available of the Courier Service
          in: integer
        type: integer
      courier_id:
        description: |-
          Courier Id of the Courier Service
          in: int
        type: integer
      courier_name:
        description: |-
          Courier Name of the Courier Service
          in: string
        type: string
      end_time:
        description: |-
          End Time of the Courier Service
          in: time
        type: string
      insurance:
        description: |-
          Insurance of the Courier Service
          in: integer
        type: integer
      insurance_fee:
        description: |-
          Insurance Fee of the Courier Service
          in: float64
        type: number
      insurance_fee_type:
        description: |-
          Insurance Fee Type of the Courier Service
          in: string
        type: string
      insurance_min:
        description: |-
          Insurance Min of the Courier Service
          in: float64
        type: number
      logo:
        description: |-
          Logo of the Courier Service
          in: string
        type: string
      max_distance:
        description: |-
          Max Distance of the Courier Service
          in: float64
        type: number
      max_purchase:
        description: |-
          Max Purchase of the Courier Service
          in: integer
        type: number
      max_volume:
        description: |-
          Max Volume of the Courier Service
          in: float64
        type: number
      max_weight:
        description: |-
          Max Weight of the Courier Service
          in: float64
        type: number
      min_purchase:
        description: |-
          Min Purchase of the Courier Service
          in: integer
        type: number
      prescription_allowed:
        description: |-
          Prescription Allowed of the Courier Service
          in: integer
        type: integer
      repickup:
        description: |-
          Repickup Fee of the Courier Service
          in: float64
        type: number
      shipping_code:
        description: |-
          Shipping Code of the Courier Service
          in: string
        type: string
      shipping_description:
        description: |-
          Shipping Description of the Courier Service
          in: string
        type: string
      shipping_name:
        description: |-
          Shipping Name of the Courier Service
          in: string
        type: string
      shipping_type:
        description: |-
          Shipping Type of the Courier Service
          in: string
        type: string
      start_time:
        description: |-
          Start Time of the Courier Service
          in: time
        type: string
      status:
        description: |-
          Status of the Courier Service
          in: integer
        type: integer
      tracking_available:
        description: |-
          Tracking Available of the Courier Service
          in: integer
        type: integer
      uid:
        description: |-
          Uid of the courier service, use this on UPDATE function
          in: string
        type: string
    type: object
info:
  contact: {}
paths:
  /courier/courier-serivces:
    get:
      consumes:
      - application/json
      description: API GetListCourierService
      parameters:
      - description: Request data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.CourierServiceListRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.CourierService'
            type: array
      security:
      - AuthorizationHeader: []
      summary: API GetListCourierService
      tags:
      - CourierService
    post:
      consumes:
      - application/json
      description: API CreateCourierService
      parameters:
      - description: Request data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.SaveCourierServiceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.CourierService'
      security:
      - AuthorizationHeader: []
      summary: API CreateCourierService
      tags:
      - CourierService
  /courier/courier-serivces/{uid}:
    delete:
      consumes:
      - application/json
      description: API DeleteCourierService
      parameters:
      - description: Request data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.GetCourierServiceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/message.Message'
      security:
      - AuthorizationHeader: []
      summary: API DeleteCourierService
      tags:
      - CourierService
    get:
      consumes:
      - application/json
      description: API GetListCourierService
      parameters:
      - description: Request data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.GetCourierServiceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.CourierService'
      security:
      - AuthorizationHeader: []
      summary: API GetListCourierService
      tags:
      - CourierService
    put:
      consumes:
      - application/json
      description: API UpdateCourierService
      parameters:
      - description: Request data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.UpdateCourierServiceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/message.Message'
      security:
      - AuthorizationHeader: []
      summary: API UpdateCourierService
      tags:
      - CourierService
swagger: "2.0"
