definitions:
  entity.Channel:
    properties:
      channel_code:
        description: |-
          ChannelCode of the Channel
          in: string
        type: string
      channel_name:
        description: |-
          ChannelName of the Channel
          in: string
        type: string
      description:
        description: |-
          Description of the Channel
          in: string
        type: string
      is_deleted:
        type: boolean
      logo:
        description: |-
          Logo of the Channel
          in: string
        type: string
      status:
        description: |-
          Status of the Channel
          in: integer
        type: integer
      uid:
        description: |-
          UID of the product
          in: int64
        type: string
    type: object
  message.Message:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  request.ChannelListRequest:
    properties:
      channelCode:
        description: |-
          ChannelCode
          in: string
        type: string
      limit:
        description: |-
          Maximun records per page
          in: int32
        maximum: 100
        minimum: 1
        type: integer
      page:
        description: |-
          Page No
          in: int32
        minimum: 1
        type: integer
      sort:
        description: |-
          Sort fields, example: name asc, uom desc
          in: string
        type: string
      status:
        description: |-
          Channel status
          in: int
        type: integer
    type: object
  request.GetChannelRequest:
    properties:
      id:
        description: |-
          name: id
          in: path
          required: true
        type: string
    type: object
  request.SaveChannelRequest:
    properties:
      channel_code:
        description: |-
          ChannelCode of the Channel
          in: string
        type: string
      channel_name:
        description: |-
          ChannelName of the Channel
          in: string
        type: string
      description:
        description: |-
          Description of the Channel
          in: string
        type: string
      logo:
        description: |-
          Logo of Channel
          in: string
        type: string
      status:
        description: |-
          status of Channel
          in: int
        type: integer
      uid:
        description: |-
          Uid of the courỉe, use this on UPDATE function
          in: int32
        type: string
    type: object
  request.UpdateChannelRequest:
    properties:
      channel_code:
        description: |-
          ChannelCode of Channel
          in: string
        type: string
      channel_name:
        description: |-
          ChannelName of the Channel
          in: string
        type: string
      description:
        description: |-
          Description of the Channel
          in: string
        type: string
      logo:
        description: |-
          Logo of Channel
          in: string
        type: string
      status:
        description: |-
          Status of Channel
          in: int
        type: integer
      uid:
        description: |-
          Uid of the Channel, use this on UPDATE function
          in: int32
        type: string
    type: object
info:
  contact: {}
paths:
  /channel/channel-app:
    get:
      consumes:
      - application/json
      description: API GetListChannel
      parameters:
      - description: Request data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ChannelListRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Channel'
            type: array
      security:
      - AuthorizationHeader: []
      tags:
      - Channel
    post:
      consumes:
      - application/json
      description: API CreateChannel
      parameters:
      - description: Request data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.SaveChannelRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/request.SaveChannelRequest'
      security:
      - AuthorizationHeader: []
      summary: API CreateChannel
      tags:
      - Channel
  /channel/channel-app/{id}:
    delete:
      consumes:
      - application/json
      description: API DeleteChannel
      parameters:
      - description: Request data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.GetChannelRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/message.Message'
      security:
      - AuthorizationHeader: []
      summary: API DeleteChannel
      tags:
      - Channel
    get:
      consumes:
      - application/json
      description: API GetChannelById
      parameters:
      - description: Request data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.GetChannelRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Channel'
      security:
      - AuthorizationHeader: []
      tags:
      - Channel
    put:
      consumes:
      - application/json
      description: API UpdateChannel
      parameters:
      - description: Request data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.UpdateChannelRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/message.Message'
      security:
      - AuthorizationHeader: []
      summary: API UpdateChannel
      tags:
      - Channel
swagger: "2.0"
