basePath: /
definitions:
  BaseIDModel:
    properties:
      is_deleted:
        type: boolean
        x-go-name: IsDeleted
      uid:
        description: |-
          UID of the product
          in: int64
        type: string
        x-go-name: UID
    type: object
    x-go-package: go-klikdokter/app/model/base
  Channel:
    properties:
      channel_code:
        description: |-
          ChannelCode of the Channel
          in: string
        type: string
        x-go-name: ChannelCode
      channel_name:
        description: |-
          ChannelName of the Channel
          in: string
        type: string
        x-go-name: ChannelName
      description:
        description: |-
          Description of the Channel
          in: string
        type: string
        x-go-name: Description
      is_deleted:
        type: boolean
        x-go-name: IsDeleted
      logo:
        description: |-
          Logo of the Channel
          in: string
        type: string
        x-go-name: Logo
      status:
        description: |-
          Status of the Channel
          in: integer
        format: int64
        type: integer
        x-go-name: Status
      uid:
        description: |-
          UID of the product
          in: int64
        type: string
        x-go-name: UID
    type: object
    x-go-package: go-klikdokter/app/model/entity
  Courier:
    properties:
      code:
        description: |-
          Code of the Courier
          in: string
        type: string
        x-go-name: Code
      courier_api_intergration:
        description: |-
          Courier Api Integration of the Courier
          in: integer
        format: int64
        type: integer
        x-go-name: CourierApiIntegration
      courier_name:
        description: |-
          Name of the Courier
          in: string
        type: string
        x-go-name: CourierName
      courier_type:
        description: |-
          Type of the Courier
          in: string
        type: string
        x-go-name: CourierType
      hide_purpose:
        description: |-
          Hide purpose of the Courier
          in: integer
        format: int64
        type: integer
        x-go-name: HidePurpose
      is_deleted:
        type: boolean
        x-go-name: IsDeleted
      logo:
        description: |-
          Logo of the Courier
          in: string
        type: string
        x-go-name: Logo
      provide_airwaybill:
        description: |-
          Provide Airwaybill of the Courier
          in: integer
        format: int64
        type: integer
        x-go-name: ProvideAirwaybill
      status:
        description: |-
          Status of the Courier
          in: integer
        format: int64
        type: integer
        x-go-name: Status
      uid:
        description: |-
          UID of the product
          in: int64
        type: string
        x-go-name: UID
      use_geocoodinate:
        description: |-
          Geo Coodinate of the Courier
          in: string
        format: int64
        type: integer
        x-go-name: UseGeocoodinate
    type: object
    x-go-package: go-klikdokter/app/model/entity
  DataResponse:
    properties:
      record:
        type: object
        x-go-name: Record
      records:
        type: object
        x-go-name: Records
    type: object
    x-go-name: data
    x-go-package: go-klikdokter/app/model/base
  MetaResponse:
    properties:
      code:
        description: |-
          Code is the response code
          in: int
        format: int64
        type: integer
        x-go-name: Code
      message:
        description: |-
          Message is the response message
          in: string
        type: string
        x-go-name: Message
    type: object
    x-go-name: metaResponse
    x-go-package: go-klikdokter/app/model/base
  PaginationResponse:
    properties:
      limit:
        format: int64
        type: integer
        x-go-name: Limit
      page:
        format: int64
        type: integer
        x-go-name: Page
      records:
        format: int64
        type: integer
        x-go-name: Records
      total_page:
        format: int64
        type: integer
        x-go-name: TotalPage
      total_records:
        format: int64
        type: integer
        x-go-name: TotalRecords
    type: object
    x-go-name: Pagination
    x-go-package: go-klikdokter/app/model/base
  SaveChannelRequest:
    properties:
      channel_code:
        description: |-
          ChannelCode of the Channel
          in: string
        type: string
        x-go-name: ChannelCode
      channel_name:
        description: |-
          ChannelName of the Channel
          in: string
        type: string
        x-go-name: ChannelName
      description:
        description: |-
          Description of the Channel
          in: string
        type: string
        x-go-name: Description
      logo:
        description: |-
          Logo of Channel
          in: string
        type: string
        x-go-name: Logo
      status:
        description: |-
          status of Channel
          in: int
        format: int64
        type: integer
        x-go-name: Status
    type: object
    x-go-package: go-klikdokter/app/model/request
  SaveCourierRequest:
    properties:
      code:
        description: |-
          Code of the courier
          in: string
        type: string
        x-go-name: Code
      courier_api_intergration:
        description: |-
          Courier Api Integration of the Courier
          in: integer
        format: int64
        type: integer
        x-go-name: CourierApiIntegration
      courier_name:
        description: |-
          Name of the courier
          in: string
        type: string
        x-go-name: CourierName
      courier_type:
        description: |-
          type of courier
          in: string
        type: string
        x-go-name: CourierType
      hide_purpose:
        description: |-
          Hide purpose of the Courier
          in: integer
        format: int64
        type: integer
        x-go-name: HidePurpose
      logo:
        description: |-
          Logo of courier
          in: string
        type: string
        x-go-name: Logo
      provide_airwaybill:
        description: |-
          Provide Airwaybill of the Courier
          in: integer
        format: int64
        type: integer
        x-go-name: ProvideAirwaybill
      status:
        description: |-
          Courier status
          in: int
        format: int64
        type: integer
        x-go-name: Status
      uid:
        description: |-
          Uid of the courỉe, use this on UPDATE function
          in: int32
        type: string
        x-go-name: Uid
      use_geocoodinate:
        description: |-
          Geo Coodinate of the Courier
          in: string
        format: int64
        type: integer
        x-go-name: UseGeocoodinate
    type: object
    x-go-package: go-klikdokter/app/model/request
  SuccessResponse:
    properties:
      data:
        $ref: '#/definitions/DataResponse'
      errors:
        description: |-
          Errors is the response message
          in: string
        type: object
        x-go-name: Errors
      meta:
        $ref: '#/definitions/MetaResponse'
      pagination:
        $ref: '#/definitions/PaginationResponse'
    type: object
    x-go-name: responseHttp
    x-go-package: go-klikdokter/app/model/base
  UpdateChannelRequest:
    properties:
      channel_code:
        description: |-
          ChannelCode of Channel
          in: string
        type: string
        x-go-name: ChannelCode
      channel_name:
        description: |-
          ChannelName of the Channel
          in: string
        type: string
        x-go-name: ChannelName
      description:
        description: |-
          Description of the Channel
          in: string
        type: string
        x-go-name: Description
      logo:
        description: |-
          Logo of Channel
          in: string
        type: string
        x-go-name: Logo
      status:
        description: |-
          Status of Channel
          in: int
        format: int64
        type: integer
        x-go-name: Status
    type: object
    x-go-package: go-klikdokter/app/model/request
host: localhost:5600
info:
  title: 'KD Boilerplate Go kit:'
  version: "1.0"
paths:
  /channel/channel-app:
    get:
      description: List of Channel Apps
      operationId: Channels
      parameters:
      - description: |-
          Maximun records per page
          in: int32
        format: int64
        in: query
        name: Limit
        type: integer
      - description: |-
          Page No
          in: int32
        format: int64
        in: query
        name: Page
        type: integer
      - example: name asc, uom desc
        in: query
        name: Sort
        type: string
      - description: |-
          Channel Code
          in: string
        in: query
        name: ChannelCode
        type: string
      - description: |-
          Channel Name
          in: string
        in: query
        name: ChannelName
        type: string
      - description: |-
          Channel Status
          in: int
        format: int64
        in: query
        name: Status
        type: integer
      responses:
        "201":
          description: SuccessResponse
          schema:
            $ref: '#/definitions/SuccessResponse'
        "401":
          description: SuccessResponse
          schema:
            $ref: '#/definitions/SuccessResponse'
      tags:
      - Channel-Apps
    post:
      description: Add Channel App
      operationId: SaveChannelRequest
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/SaveChannelRequest'
        x-go-name: Body
      responses:
        "201":
          description: SuccessResponse
          schema:
            $ref: '#/definitions/SuccessResponse'
        "401":
          description: SuccessResponse
          schema:
            $ref: '#/definitions/SuccessResponse'
      tags:
      - Channel-Apps
  /channel/channel-app/{uid}:
    delete:
      description: Delete Channel Apps by uid
      operationId: ChannelRequestDeleteByUid
      parameters:
      - description: Uid of the Channel
        in: path
        name: uid
        required: true
        type: string
        x-go-name: UId
      responses:
        "200":
          description: SuccessResponse
          schema:
            $ref: '#/definitions/SuccessResponse'
        "401":
          description: SuccessResponse
          schema:
            $ref: '#/definitions/SuccessResponse'
      tags:
      - Channel-Apps
    get:
      description: Get Detail of Channel Apps
      operationId: ChannelRequestGetByUid
      parameters:
      - description: Uid of the Channel
        in: path
        name: uid
        required: true
        type: string
        x-go-name: UId
      responses:
        "201":
          description: SuccessResponse
          schema:
            $ref: '#/definitions/SuccessResponse'
        "401":
          description: SuccessResponse
          schema:
            $ref: '#/definitions/SuccessResponse'
      tags:
      - Channel-Apps
    put:
      description: Update Channel App by uid
      operationId: UpdateChannelRequest
      parameters:
      - description: Uid of the Channel
        in: path
        name: uid
        required: true
        type: string
        x-go-name: UId
      - in: body
        name: body
        schema:
          $ref: '#/definitions/UpdateChannelRequest'
        x-go-name: Body
      responses:
        "200":
          description: SuccessResponse
          schema:
            $ref: '#/definitions/SuccessResponse'
        "401":
          description: SuccessResponse
          schema:
            $ref: '#/definitions/SuccessResponse'
      tags:
      - Channel-Apps
  /courier/{id}:
    put:
      description: Update courier
      operationId: UpdateCourierRequest
      responses:
        "200":
          description: SuccessResponse
          schema:
            $ref: '#/definitions/SuccessResponse'
        "401":
          description: SuccessResponse
          schema:
            $ref: '#/definitions/SuccessResponse'
      tags:
      - courier-update
  /courier/courier:
    post:
      description: Manage Courier
      operationId: ManagedCourierRequest
      responses:
        "201":
          description: SuccessResponse
          schema:
            $ref: '#/definitions/SuccessResponse'
        "401":
          description: SuccessResponse
          schema:
            $ref: '#/definitions/SuccessResponse'
      tags:
      - Courier
  /courier/courier/{id}:
    delete:
      description: Delete courier
      operationId: byParamDelete
      responses:
        "200":
          description: SuccessResponse
          schema:
            $ref: '#/definitions/SuccessResponse'
        "401":
          description: SuccessResponse
          schema:
            $ref: '#/definitions/SuccessResponse'
      tags:
      - courier-delete
    get:
      description: Get Courier
      operationId: Courier
      responses:
        "201":
          description: SuccessResponse
          schema:
            $ref: '#/definitions/SuccessResponse'
        "401":
          description: SuccessResponse
          schema:
            $ref: '#/definitions/SuccessResponse'
      tags:
      - Get-Courier
produces:
- application/json
schemes:
- http
swagger: "2.0"
