## Builder
FROM golang:1.16-alpine AS builder

ENV GO111MODULE=on

RUN apk update && apk upgrade && apk add --no-cache git gcc libc-dev make openssl

WORKDIR /app
COPY . .

RUN go get

RUN git clone https://github.com/go-swagger/go-swagger && cd go-swagger && go install ./cmd/swagger
RUN swagger generate spec -o swagger.yaml --scan-models
RUN sed -i 's|localhost:5600|shipping-svc.medkomtek-stg.com|g' swagger.yaml && sed -i 's/\- https//g' swagger.yaml && sed -i "s|- http|- https|g" swagger.yaml && rm -rf go-swagger

RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o /go/bin/shipping-svc

## Distribution
FROM alpine:latest

ENV KD_ENV=prd
ENV TZ="Asia/Jakarta"

RUN apk update && apk upgrade && apk add --no-cache tzdata
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /app
COPY --from=builder /app /app
COPY --from=builder /go/bin /go/bin

EXPOSE 5600

RUN chmod +x /go/bin/shipping-svc

CMD ["/go/bin/shipping-svc"]
